// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcUkTgEEmzh_nBjOpjuLQQrwoz5JWaXO4',
    appId: '1:949836122742:web:65a50da77896b846c66d57',
    messagingSenderId: '949836122742',
    projectId: 'habittrackingapp-41dc1',
    authDomain: 'habittrackingapp-41dc1.firebaseapp.com',
    storageBucket: 'habittrackingapp-41dc1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnyK2QdgW-J21ywyLd2gsUDnfGOYek6sc',
    appId: '1:949836122742:android:e886f5f2cd4c25c2c66d57',
    messagingSenderId: '949836122742',
    projectId: 'habittrackingapp-41dc1',
    storageBucket: 'habittrackingapp-41dc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqZAp22RjJNyFXNkkJ7lpNgvvJya49XPs',
    appId: '1:949836122742:ios:bcb2eb5d9da844c2c66d57',
    messagingSenderId: '949836122742',
    projectId: 'habittrackingapp-41dc1',
    storageBucket: 'habittrackingapp-41dc1.firebasestorage.app',
    iosBundleId: 'com.abhishek.habittrackingapp',
  );
}
