// utils/local_quotes.dart
final Map<String, List<String>> localQuotes = {
  "Motivation": [
    "Believe in yourself and all that you are.",
    "Small steps in the right direction can turn out to be the biggest step of your life.",
    "Don't wait for opportunity. Create it.",
    "Your only limit is you.",
    "Hard work beats talent when talent doesn’t work hard.",
    "Stay positive, work hard, make it happen.",
    "Success is the sum of small efforts repeated day in and day out.",
    "Dream big. Start small. Act now.",
    "The key to success is to focus on goals, not obstacles.",
    "What you do today can improve all your tomorrows."
  ],
  "Discipline": [
    "Discipline is the silent force behind every success story.",
    "Small consistent actions lead to big results.",
    "The secret to success is staying disciplined even when no one is watching.",
    "Discipline is doing what needs to be done, even when you don’t feel like it.",
    "Focus on progress, not perfection.",
    "Your future is created by what you do today, not tomorrow.",
    "Discipline is the difference between dreams and reality.",
    "Consistency compounds over time.",
    "Strong habits build strong results.",
    "Control your mind, control your life."
  ],
  "Success": [
    "Success is earned, not given.",
    "Great achievements start with a single step.",
    "Success comes to those who persist when others quit.",
    "Dream big, work hard, stay focused.",
    "Your actions today shape your success tomorrow.",
    "Success is the result of preparation meeting opportunity.",
    "Don’t chase success—chase excellence, and success will follow.",
    "The harder you work, the luckier you get.",
    "Success is built on a foundation of failure and learning.",
    "Every small effort counts toward your big goal."
  ],
  "Habits": [
    "Small consistent habits lead to extraordinary results.",
    "Your daily habits shape your destiny.",
    "Greatness is built one habit at a time.",
    "Discipline your mind, and your habits will follow.",
    "Habits are the invisible architecture of your life.",
    "Focus on creating habits, not just goals.",
    "Every action you repeat becomes a part of who you are.",
    "Positive habits compound into positive results.",
    "Change your habits, change your life.",
    "The secret of your future is hidden in your daily routines."
  ],
  "Growth": [
    "Personal growth starts with self-awareness.",
    "To grow, you must embrace discomfort and uncertainty.",
    "Every challenge is an opportunity to grow stronger.",
    "Growth happens when you step outside what’s familiar.",
    "Invest in yourself; your growth is your greatest asset.",
    "The journey of growth is continuous—never stop learning.",
    "Mistakes are lessons that fuel growth.",
    "True growth comes from facing your fears.",
    "Your mindset determines the height of your growth.",
    "Small improvements every day lead to massive growth over time."
  ],
  "Wisdom": [
    "The only true wisdom is in knowing you know nothing.",
    "Turn your wounds into wisdom.",
    "Knowing yourself is the beginning of all wisdom.",
    "A wise man learns more from his enemies than a fool from his friends.",
    "Knowledge speaks, but wisdom listens.",
    "Wisdom is the reward you get for a lifetime of listening.",
    "The invariable mark of wisdom is to see the miraculous in the common.",
    "Patience is the companion of wisdom.",
    "Silence is the sleep that nourishes wisdom.",
    "Wisdom begins in wonder.",
  ],
  "Mindfulness": [
    "The present moment is filled with joy and happiness.",
    "Mindfulness is the aware, balanced acceptance of the present experience.",
    "Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.",
    "Walk as if you are kissing the Earth with your feet.",
    "Mindfulness isn’t difficult, we just need to remember to do it.",
    "Breathe in deeply to bring your mind home to your body.",
    "Every morning we are born again. What we do today is what matters most.",
    "Be where you are, not where you think you should be.",
    "Peace comes from within. Do not seek it without.",
    "Smile, breathe, and go slowly.",
  ],
};